// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAReWQLrwo8pojhSptqLTaB2p_CTk-QoDk',
    appId: '1:593260128689:web:cc7803af0c97b5670b3590',
    messagingSenderId: '593260128689',
    projectId: 'inventario-7d2d1',
    authDomain: 'inventario-7d2d1.firebaseapp.com',
    storageBucket: 'inventario-7d2d1.firebasestorage.app',
    measurementId: 'G-653JSCF7TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOR0-GSgjx3CiZgYpFpcEJoVs8h0f8l64',
    appId: '1:593260128689:android:382c8c1f4613f6f00b3590',
    messagingSenderId: '593260128689',
    projectId: 'inventario-7d2d1',
    storageBucket: 'inventario-7d2d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzHPCZ9Iag1icC56SA49uqIXONdOxC5OE',
    appId: '1:593260128689:ios:d93f40f7a3f25e810b3590',
    messagingSenderId: '593260128689',
    projectId: 'inventario-7d2d1',
    storageBucket: 'inventario-7d2d1.firebasestorage.app',
    iosBundleId: 'com.example.inventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzHPCZ9Iag1icC56SA49uqIXONdOxC5OE',
    appId: '1:593260128689:ios:d93f40f7a3f25e810b3590',
    messagingSenderId: '593260128689',
    projectId: 'inventario-7d2d1',
    storageBucket: 'inventario-7d2d1.firebasestorage.app',
    iosBundleId: 'com.example.inventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAReWQLrwo8pojhSptqLTaB2p_CTk-QoDk',
    appId: '1:593260128689:web:94dce75230b9d5ec0b3590',
    messagingSenderId: '593260128689',
    projectId: 'inventario-7d2d1',
    authDomain: 'inventario-7d2d1.firebaseapp.com',
    storageBucket: 'inventario-7d2d1.firebasestorage.app',
    measurementId: 'G-E3CT5D4928',
  );
}
